-- ID, NAME, TOTSAL
/*
    PRODUCT - PID, NAME, PRICE
    ORDER - PID, AMOUNT, PDATE
*/
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) TOTAL_SALES
FROM (
    SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE,
            O.AMOUNT
    FROM FOOD_PRODUCT P
        JOIN FOOD_ORDER O
            ON P.PRODUCT_ID = O.PRODUCT_ID
    WHERE O.PRODUCE_DATE BETWEEN 
        '2022-05-01 00:00:00' AND '2022-05-31 23:59:59') T
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;