-- 코드를 입력하세요
# SELECT * FROM PRODUCT;
# SELECT sum(sales_amount) FROM OFFLINE_SALE 
# GROUP BY PRODUCT_ID;
# SELECT * FROM OFFLINE_SALE 

#     SELECT PRODUCT_CODE, SUM(sales_amount) AS TOTAL_SALES
#     FROM OFFLINE_SALE
#     GROUP BY PRODUCT_CODE
# ) O ON O.PRODUCT_CODE = P.PRODUCT_CODE

SELECT P.PRODUCT_CODE, P.PRICE * O.QUANTITYS as SALES
FROM PRODUCT P 
LEFT JOIN (
    SELECT PRODUCT_ID, SUM(sales_amount) as QUANTITYS 
    FROM OFFLINE_SALE 
    GROUP BY PRODUCT_ID
) O ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IN(
    SELECT DISTINCT O.PRODUCT_ID FROM OFFLINE_SALE O
    WHERE P.PRODUCT_ID = O.PRODUCT_ID
    GROUP BY O.PRODUCT_ID
)
ORDER BY SALES desc, P.PRODUCT_CODE asc;