-- 코드를 작성해주세요
SELECT ROUTE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 2), 'km') TOTAL_DISTANCE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST) / COUNT(*), 2), 'km') AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;