-- 코드를 작성해주세요
# SELECT * FROM HR_DEPARTMENT;

SELECT HE.DEPT_ID, HD.DEPT_NAME_EN, ROUND(SUM(SAL) / COUNT(*), 0) AS AVG_SAL
FROM HR_EMPLOYEES HE
INNER JOIN HR_DEPARTMENT HD
ON HE.DEPT_ID = HD.DEPT_ID
GROUP BY HE.DEPT_ID
ORDER BY AVG_SAL DESC;