-- 코드를 작성해주세요
SELECT E3_ID "ID" 
FROM (
    SELECT E.*, E3.ID "E3_ID"
    FROM (
        SELECT E1.PARENT_ID "E1_PID", E1.ID "E1_ID", E2.ID "E2_ID"
        FROM ECOLI_DATA E1
        INNER JOIN ECOLI_DATA E2
        ON E1.ID = E2.PARENT_ID
    ) E
    INNER JOIN ECOLI_DATA E3
    ON E.E2_ID = E3.PARENT_ID
) T
WHERE E1_PID IS NULL
ORDER BY E3_ID ASC;

