-- 코드를 입력하세요
SELECT FLAVOR
FROM(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR

    UNION

    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) T
GROUP BY FLAVOR
HAVING SUM(TOTAL_ORDER)
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;
